### PR TITLE
Koski fixes

### LINKED ISSUE #659: Perusopetuksen lisätiedot

### LINKED ISSUE #660: Local subjects coursecode
Local subjects may have overlapping or incomplete course codes (subject code + coursenumber).

### LINKED ISSUE #661: Religion subjects split
Split the religion subjects according to the new subject codes (lukio/pk).

### LINKED ISSUE #663: Extra-ympäristön tiedonsiirtovirheet
Seuraavat ongelmat havaittu testauksessa:
* Internetix-opiskelijoita ei voida siirtää, kun niillä ei ole suorituksia(/ainevalintaa)
* <strike>Samanaikainen muokkaus</strike> Korjattu aiemmin
* <strike>Valmiiksi merkityllä suorituksella suorituksentyyppi/aikuistenperusopetuksenoppimaaranalkuvaihe on keskeneräinen osasuoritus ma</strike> Korjattu aiemmin
* <strike>Valmiiksi merkityllä suorituksella koulutus/201101 on keskeneräinen osasuoritus ENA</strike> Korjattu aiemmin
* <strike>Valmiiksi merkityllä suorituksella koulutus/309902 on keskeneräinen osasuoritus koskioppiaineetyleissivistava/OP</strike> Korjattu aiemmin

### PR DESCRIPTION
**Pull request by anttiviljakainen**
Includes PR #658 

Closes #659 
Closes #661 
Closes #660 
Closes #663

### CODE REVIEW

File: framework/src/main/java/fi/otavanopisto/pyramus/koski/KoskiAikuistenPerusopetuksenStudentHandler.java [hunk 1]
```diff
@@ -121,11 +131,41 @@ public Opiskeluoikeus studentToModel(Student student, String academyIdentifier,
...
+    for (StudentLodgingPeriod lodgingPeriod : lodgingPeriods) {
+      lisatiedot.addSisaoppilaitosmainenMajoitus(new Majoitusjakso(lodgingPeriod.getBegin(), lodgingPeriod.getEnd()));
+    }
+    
+    if (!lodgingPeriods.isEmpty()) {
+      Date minBeginDate = lodgingPeriods.stream().map(StudentLodgingPeriod::getBegin).filter(Objects::nonNull)
+          .min(Comparator.nullsLast(Date::compareTo)).orElse(null);
+      
+      if (minBeginDate != null) {
+        Date maxEndDate = lodgingPeriods.stream().map(StudentLodgingPeriod::getEnd).filter(Objects::nonNull)
```
Comment (ilmoeuro) [inline framework/src/main/java/fi/otavanopisto/pyramus/koski/KoskiAikuistenPerusopetuksenStudentHandler.java]: Lookin' good!
