### PR TITLE
Fixes #710 REST endpoint for updating user credentials fails to check

### LINKED ISSUE #710: REST endpoint for updating user credentials fails to check username owner
PersonRESTService has an endpoint for updating user credentials but it does not check whether the username it receives belongs to some other user. If so, that should result in some suitable HTTP error (e.g. 409 - Conflict).

### PR DESCRIPTION
**Pull request by saaralepisto**
Fixes #710 REST endpoint for updating user credentials fails to check username owner

### CODE REVIEW

File: pyramus/src/main/java/fi/otavanopisto/pyramus/plugin/auth/internal/InternalAuthenticationStrategy.java [hunk 1]
```diff
@@ -131,6 +131,26 @@ public User getUser(String username, String password) {
...
+    InternalAuthDAO internalAuthDAO = DAOFactory.getInstance().getInternalAuthDAO(); 
+    
+    InternalAuth internalAuth = internalAuthDAO.findByUsername(username);
+    if (internalAuth != null) {
+      UserIdentification userIdentification = userIdentificationDAO.findByAuthSourceAndExternalId(getName(), String.valueOf(internalAuth.getId()));
+      if(userIdentification != null){
+        
+        return userIdentification.getPerson().getDefaultUser();
+      }
+      logger.warning("UserIdentification is null");
```
Comment (pkukkon) [inline pyramus/src/main/java/fi/otavanopisto/pyramus/plugin/auth/internal/InternalAuthenticationStrategy.java]: No need to log warning. Since this method is probably used to test whether a username is available, the given username not belonging to anyone is perfectly normal and simply returns null;

File: rest/src/main/java/fi/otavanopisto/pyramus/rest/PersonRESTService.java [hunk 2]
```diff
@@ -329,7 +331,19 @@ public Response updateCredentials(@PathParam("ID") Long id, UserCredentials user
                 userIdentificationDAO.updateExternalId(userIdentification, externalId);
               } else {
                 // Check that old password matches
+                User userByName = internalAuthenticationProvider.getUserByName(newUserName);
+                boolean usernameExists;
+                
+                if (userByName != null) {
```
Comment (pkukkon) [inline rest/src/main/java/fi/otavanopisto/pyramus/rest/PersonRESTService.java]: If the username belongs to the user who is changing their credentials then that's perfectly fine. With this implementation, the user is forced to also change their username whenever they want to change their password :)
